package proofpool

// ProofPool is a pool for storing and propagating proofs that have been generated by extensions.

type Proof struct {
	ProofType   string            // e.g., "Groth16"
	ExtensionID string            // erc4337
	Inputs      map[string][]byte // Public inputs
	Output      []byte            // Post-processed result data (e.g., calldata)
	ProofData   []byte            // The proof itself (binary blob)
	Metadata    map[string]string // Optional metadata (versioning, etc.) MUST include "CircuitHash"
}

type Pool struct {
}
